IMGUR_CLIENT_ID=XXXXXX \
HUBOT_ARTSY_CLIENT_ID=XXXXXX \
HUBOT_ARTSY_CLIENT_SECRET=XXXXXX \
HUBOT_PIVOTAL_API_TOKEN=XXXXXX \
HUBOT_PIVOTAL_PROJECT_ID=XXXXXX \
HUBOT_BITLY_ACCESS_TOKEN=XXXXXX \
./bin/hubot --name freddie
